services:
  analytics-prod-db:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: analytics-prod-workgroup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: